on:
  push:
    branches:
      - fulcrum-api
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/packages/fulcrum-api && npm install
        cd $GITHUB_WORKSPACE/packages/fulcrum-api && npm run build
    - name: deploy to server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: "$GITHUB_WORKSPACE"
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
